version: '3'

services:
  bob:
    build: .
    depends_on:
      - db
    networks:
      - bobweb

#  web:
#    # build: .
#    command: python3 manage.py runserver 0.0.0.0:8000
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    networks:
#      - bobweb

  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    networks:
      - bobweb
    environment:
      POSTGRES_DB: bob
      POSTGRES_USER: bob
      POSTGRES_PASSWORD: bob

networks:
  bobweb: